version = "1.0"

[main]
name = "Glitchsoc configuration"
services = ["__APP__-web", "__APP__-sidekiq", "__APP__-streaming"]

    [main.customization]
    name = "Customization"
        
        [main.customization.max_toot_chars]
        ask = "Maximum allowed character count in a toot"
        type = "number"
        example = "500"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_pinned_toots]
        ask = "Maximum number of pinned posts"
        type = "number"
        example = "5"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_bio_chars]
        ask = "Maximum allowed bio characters"
        type = "number"
        example = "500"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_profile_fields]
        ask = "Maximim number of profile fields allowed"
        type = "number"
        example = "4"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_display_name_chars]
        ask = "Maximum allowed bio characters"
        type = "number"
        example = "30"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_poll_options]
        ask = "Maximum allowed poll options"
        type = "number"
        example = "5"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_poll_option_chars]
        ask = "Maximum allowed poll option characters"
        type = "number"
        example = "100"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_image_size]
        ask = "Maximum image upload size, in bytes"
        type = "number"
        example = "8388608"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_video_size]
        ask = "Maximum video and audio upload sizes, in bytes"
        type = "number"
        example = "41943040"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_emoji_size]
        ask = "Maximum custom emoji file sizes"
        type = "number"
        example = "51200"
        bind = ":__FINALPATH____/live/.env.production"

        [main.customization.max_remote_emoji_size]
        ask = "Maximum remote custom emoji file sizes"
        type = "number"
        example = "204800"
        bind = ":__FINALPATH__/live/.env.production"
