test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi", "change_url"]
    # The test IDs to be used in only/exclude statements are: install.root, install.subdir, install.nourl, install.multi, backup_restore, upgrade, upgrade.someCommitId change_url
    # NB: you should NOT need this except if you really have a good reason...


    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # Use defaults from manifest.toml

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9c7a5ae.name = "Upgrade from 2023.06.19~ynh1"
